#include "Config.h"
#include <fstream>
#include <iostream>
#include <algorithm>
#include "nvse/PluginAPI.h"

// Singleton instance
Config& Config::GetInstance() {
    static Config instance;
    return instance;
}

// Constructor
Config::Config() : m_filename(""), m_fullPath("") {
    InitializeDefaultConfig();
}

// Initialize with default configuration values
void Config::InitializeDefaultConfig() {
    std::lock_guard<std::mutex> lock(m_mutex);

    // Network settings
    m_config["Network.ServerAddress"] = "127.0.0.1";
    m_config["Network.ServerPort"] = "25575";
    m_config["Network.ReconnectInterval"] = "60"; // Seconds
    m_config["Network.MaxReconnectAttempts"] = "5";
    m_config["Network.ConnectionTimeout"] = "5"; // Seconds
    m_config["Network.SaveGameReconnectAttempts"] = "2"; // Number of reconnect attempts when loading a save
    m_config["Network.SaveGameReconnectDelay"] = "1000"; // Milliseconds between reconnect attempts when loading a save

    // Client settings
    m_config["Client.Version"] = "1.0";
    m_config["Client.LogLevel"] = "INFO";

    // Security settings
    m_config["Security.Password"] = "";  // Empty for no password
}

// Load configuration from a file
bool Config::Load(const void* nvseInterface, const std::string& filename) {
    NVSEInterface* nvse = (NVSEInterface*)nvseInterface;

    // Get full path to ini file
    m_fullPath = std::string(nvse->GetRuntimeDirectory()) + "/Data/NVSE/Plugins/" + filename;
    m_filename = filename;

    // Check if file exists
    std::ifstream checkFile(m_fullPath);
    bool fileExists = checkFile.good();
    checkFile.close();

    // If file doesn't exist, create it with default values
    if (!fileExists) {
        std::cout << "Config file not found: " << m_fullPath << ", creating with default values" << std::endl;

        // Create a temporary config with default values
        std::map<std::string, std::string> defaultConfig;

        // Network settings
        defaultConfig["Network.ServerAddress"] = "127.0.0.1";
        defaultConfig["Network.ServerPort"] = "25575";
        defaultConfig["Network.ReconnectInterval"] = "60"; // Seconds
        defaultConfig["Network.MaxReconnectAttempts"] = "5";
        defaultConfig["Network.ConnectionTimeout"] = "5"; // Seconds
        defaultConfig["Network.SaveGameReconnectAttempts"] = "2"; // Number of reconnect attempts when loading a save
        defaultConfig["Network.SaveGameReconnectDelay"] = "1000"; // Milliseconds between reconnect attempts when loading a save

        // Client settings
        defaultConfig["Client.Version"] = "1.0";
        defaultConfig["Client.LogLevel"] = "INFO";

        // Security settings
        defaultConfig["Security.Password"] = "";  // Empty for no password

        // Write the default config to file
        std::ofstream file(m_fullPath);
        if (!file.is_open()) {
            std::cerr << "Failed to create default configuration file: " << m_fullPath << std::endl;
            return false;
        }

        // Write the config file with sections and comments
        file << "# Quest Sync NVSE Plugin Configuration" << std::endl;
        file << "# This file is automatically generated if it doesn't exist" << std::endl;
        file << std::endl;

        // Group settings by section
        std::map<std::string, std::map<std::string, std::string>> sections;
        for (const auto& pair : defaultConfig) {
            std::string key = pair.first;
            std::string section = key.substr(0, key.find('.'));
            std::string setting = key.substr(key.find('.') + 1);
            sections[section][setting] = pair.second;
        }

        // Write each section
        for (const auto& section : sections) {
            file << "[" << section.first << "]" << std::endl;

            for (const auto& pair : section.second) {
                // Add comments for each setting
                if (section.first == "Network") {
                    if (pair.first == "ServerAddress") {
                        file << "# The IP address of the Quest Sync server" << std::endl;
                    }
                    else if (pair.first == "ServerPort") {
                        file << "# The port of the Quest Sync server" << std::endl;
                    }
                    else if (pair.first == "ReconnectInterval") {
                        file << "# Time in seconds between reconnection attempts" << std::endl;
                    }
                    else if (pair.first == "MaxReconnectAttempts") {
                        file << "# Maximum number of reconnection attempts" << std::endl;
                    }
                    else if (pair.first == "ConnectionTimeout") {
                        file << "# Connection timeout in seconds" << std::endl;
                    }

                    else if (pair.first == "SaveGameReconnectAttempts") {
                        file << "# Number of reconnect attempts when loading a save game (0 to disable)" << std::endl;
                    }
                    else if (pair.first == "SaveGameReconnectDelay") {
                        file << "# Milliseconds between reconnect attempts when loading a save game" << std::endl;
                    }
                }
                else if (section.first == "Client") {
                    if (pair.first == "Version") {
                        file << "# Client version (do not change manually)" << std::endl;
                    }
                    else if (pair.first == "LogLevel") {
                        file << "# Log level (DEBUG, INFO, WARNING, ERROR)" << std::endl;
                    }
                }
                else if (section.first == "Security") {
                    if (pair.first == "Password") {
                        file << "# Password for server authentication (leave empty if server has no password)" << std::endl;
                    }
                }

                file << pair.first << "=" << pair.second << std::endl;
            }

            // Add a blank line between sections
            file << std::endl;
        }

        file.close();
        std::cout << "Created default configuration file: " << m_fullPath << std::endl;

        // Now set the config in memory
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            m_config = defaultConfig;
        }

        return true;
    }

    // File exists, load it
    std::map<std::string, std::string> loadedConfig;
    std::ifstream file(m_fullPath);
    if (!file.is_open()) {
        std::cerr << "Failed to open existing configuration file: " << m_fullPath << std::endl;
        return false;
    }

    // Read the config file
    std::string line;
    std::string section;
    while (std::getline(file, line)) {
        // Trim whitespace
        Trim(line);

        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }

        // Check for section header
        if (line[0] == '[' && line[line.length() - 1] == ']') {
            section = line.substr(1, line.length() - 2);
            continue;
        }

        // Parse key-value pair
        size_t delimPos = line.find('=');
        if (delimPos != std::string::npos) {
            std::string key = line.substr(0, delimPos);
            std::string value = line.substr(delimPos + 1);

            // Trim key and value
            Trim(key);
            Trim(value);

            // Store in config map with section prefix
            if (!section.empty()) {
                loadedConfig[section + "." + key] = value;
            }
            else {
                loadedConfig[key] = value;
            }
        }
    }

    file.close();
    std::cout << "Configuration loaded from " << m_fullPath << std::endl;

    // Check for missing settings and add defaults
    bool configUpdated = false;
    std::map<std::string, std::string> defaultConfig;

    // Network settings
    defaultConfig["Network.ServerAddress"] = "127.0.0.1";
    defaultConfig["Network.ServerPort"] = "25575";
    defaultConfig["Network.ReconnectInterval"] = "60"; // Seconds
    defaultConfig["Network.MaxReconnectAttempts"] = "5";
    defaultConfig["Network.ConnectionTimeout"] = "5"; // Seconds
    defaultConfig["Network.SaveGameReconnectAttempts"] = "2"; // Number of reconnect attempts when loading a save
    defaultConfig["Network.SaveGameReconnectDelay"] = "1000"; // Milliseconds between reconnect attempts when loading a save

    // Client settings
    defaultConfig["Client.Version"] = "1.0";
    defaultConfig["Client.LogLevel"] = "INFO";

    // Security settings
    defaultConfig["Security.Password"] = "";  // Empty for no password

    for (const auto& pair : defaultConfig) {
        if (loadedConfig.find(pair.first) == loadedConfig.end()) {
            loadedConfig[pair.first] = pair.second;
            std::cout << "Added missing config setting: " << pair.first << "=" << pair.second << std::endl;
            configUpdated = true;
        }
    }

    // Update the config in memory
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        m_config = loadedConfig;
    }

    // If config was updated with missing settings, save it back to file
    if (configUpdated) {
        Save();
    }

    return true;
}
// Save configuration to the current file
bool Config::Save() {
    if (m_fullPath.empty()) {
        std::cerr << "Cannot save configuration: no file path set" << std::endl;
        return false;
    }

    // Get a copy of the current config
    std::map<std::string, std::string> currentConfig;
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        currentConfig = m_config;
    }

    // Group settings by section
    std::map<std::string, std::map<std::string, std::string>> sections;
    for (const auto& pair : currentConfig) {
        std::string key = pair.first;
        size_t dotPos = key.find('.');
        if (dotPos != std::string::npos) {
            std::string section = key.substr(0, dotPos);
            std::string setting = key.substr(dotPos + 1);
            sections[section][setting] = pair.second;
        }
        else {
            // Handle keys without a section
            sections[""][key] = pair.second;
        }
    }

    // Write to file
    std::ofstream file(m_fullPath);
    if (!file.is_open()) {
        std::cerr << "Failed to open configuration file for writing: " << m_fullPath << std::endl;
        return false;
    }

    // Write header
    file << "# Quest Sync NVSE Plugin Configuration" << std::endl;
    file << "# Last updated: " << __DATE__ << " " << __TIME__ << std::endl;
    file << std::endl;

    // Write each section
    for (const auto& section : sections) {
        // Skip empty section name for now
        if (!section.first.empty()) {
            file << "[" << section.first << "]" << std::endl;

            for (const auto& pair : section.second) {
                // Add comments for each setting
                if (section.first == "Network") {
                    if (pair.first == "ServerAddress") {
                        file << "# The IP address of the Quest Sync server" << std::endl;
                    }
                    else if (pair.first == "ServerPort") {
                        file << "# The port of the Quest Sync server" << std::endl;
                    }
                    else if (pair.first == "ReconnectInterval") {
                        file << "# Time in seconds between reconnection attempts" << std::endl;
                    }
                    else if (pair.first == "MaxReconnectAttempts") {
                        file << "# Maximum number of reconnection attempts" << std::endl;
                    }
                    else if (pair.first == "ConnectionTimeout") {
                        file << "# Connection timeout in seconds" << std::endl;
                    }

                    else if (pair.first == "SaveGameReconnectAttempts") {
                        file << "# Number of reconnect attempts when loading a save game (0 to disable)" << std::endl;
                    }
                    else if (pair.first == "SaveGameReconnectDelay") {
                        file << "# Milliseconds between reconnect attempts when loading a save game" << std::endl;
                    }
                }
                else if (section.first == "Client") {
                    if (pair.first == "Version") {
                        file << "# Client version (do not change manually)" << std::endl;
                    }
                    else if (pair.first == "LogLevel") {
                        file << "# Log level (DEBUG, INFO, WARNING, ERROR)" << std::endl;
                    }
                }
                else if (section.first == "Security") {
                    if (pair.first == "Password") {
                        file << "# Password for server authentication (leave empty if server has no password)" << std::endl;
                    }
                }

                file << pair.first << "=" << pair.second << std::endl;
            }

            // Add a blank line between sections
            file << std::endl;
        }
    }

    // Write settings without a section at the end
    if (sections.find("") != sections.end()) {
        for (const auto& pair : sections[""]) {
            file << pair.first << "=" << pair.second << std::endl;
        }
    }

    file.close();
    std::cout << "Configuration saved to " << m_fullPath << std::endl;

    return true;
}

// Get a string value from the configuration
std::string Config::GetString(const std::string& key, const std::string& defaultValue) {
    std::lock_guard<std::mutex> lock(m_mutex);
    auto it = m_config.find(key);
    if (it != m_config.end()) {
        return it->second;
    }
    return defaultValue;
}

// Get an integer value from the configuration
int Config::GetInt(const std::string& key, int defaultValue) {
    std::string strValue = GetString(key, "");
    if (strValue.empty()) {
        return defaultValue;
    }

    try {
        return std::stoi(strValue);
    }
    catch (const std::exception&) {
        return defaultValue;
    }
}

// Get a boolean value from the configuration
bool Config::GetBool(const std::string& key, bool defaultValue) {
    std::string strValue = GetString(key, "");
    if (strValue.empty()) {
        return defaultValue;
    }

    // Convert to lowercase
    std::transform(strValue.begin(), strValue.end(), strValue.begin(),
        [](unsigned char c) { return std::tolower(c); });

    // Check for true values
    if (strValue == "true" || strValue == "yes" || strValue == "1" || strValue == "on") {
        return true;
    }

    // Check for false values
    if (strValue == "false" || strValue == "no" || strValue == "0" || strValue == "off") {
        return false;
    }

    return defaultValue;
}

// Set a string value in the configuration
void Config::SetString(const std::string& key, const std::string& value) {
    std::lock_guard<std::mutex> lock(m_mutex);
    m_config[key] = value;
}

// Set an integer value in the configuration
void Config::SetInt(const std::string& key, int value) {
    SetString(key, std::to_string(value));
}

// Set a boolean value in the configuration
void Config::SetBool(const std::string& key, bool value) {
    SetString(key, value ? "true" : "false");
}

// Trim whitespace from a string
void Config::Trim(std::string& str) {
    // Trim leading whitespace
    str.erase(str.begin(), std::find_if(str.begin(), str.end(), [](unsigned char ch) {
        return !std::isspace(ch);
    }));

    // Trim trailing whitespace
    str.erase(std::find_if(str.rbegin(), str.rend(), [](unsigned char ch) {
        return !std::isspace(ch);
    }).base(), str.end());
}
